### PR TITLE
#43 - fixing application.properties files not overloading with multimodule setup

### LINKED ISSUE #43: Compose fails to build backend
Application fails to start, datasource bean throws exception for invalid driver class.
Unsure if invalid beans are a cascading failure from datasource, of if there are multiple issues.

Run docker compose up -d to create stack
Review backend logs from EDPN stack in docker.

### PR DESCRIPTION
**Pull request by pveeckhout**
the application.properties files are not being overloaded, the spring boot app will use just any one on the classpath, but not "merge" them.

therefore I moved the config to a file named after the module and loaded it via @PropertiesSources annotation.
I also added a name to all config files to prevent conflicts in the future.
Idem with the liquibase migration files

### CODE REVIEW

File: trade-module/src/main/java/io/edpn/backend/trade/configuration/PropertyConfig.java
Comment (Daniel-J-Mason) [inline trade-module/src/main/java/io/edpn/backend/trade/configuration/PropertyConfig.java:1]: The second PropertySource causes trademodule-local.properties to be loaded when using docker compose up -d --build. (Thus crashing backend container due to it looking for postgres at 54321)

Deleting this line allows the full stack to run. Must find a different way to implement. Typically you could do something like :
@PropertySource("classpath:${spring.profiles.active}.properties")
But since these profiles are now named per module it gets a bit more complex.

**Review by Daniel-J-Mason — CHANGES_REQUESTED** [review]

File: trade-module/src/main/java/io/edpn/backend/trade/configuration/PropertyConfig.java
Comment (pveeckhout) [reply trade-module/src/main/java/io/edpn/backend/trade/configuration/PropertyConfig.java:1]: fixed by leveraging includes in the main application properties file

File: boot/src/main/java/module-info.java [hunk 1]
```diff
@@ -1,4 +1,4 @@
-module edpn.boot {
+module io.edpn.backend.boot {
```
Comment (jixxed) [inline boot/src/main/java/module-info.java]: module name != package name. It can cause confusion if these are named exactly the same.

Comment (pveeckhout) [reply boot/src/main/java/module-info.java]: should be fixed

**Review by jixxed — APPROVED** [review]

**Review by Daniel-J-Mason — APPROVED** [review]
